### PR TITLE
Revisi formatting

### PR DESCRIPTION
**Pull request by aldihsuhandi**

### CODE REVIEW

**Review by timothyjulian — COMMENTED** [review]
Lgtm

**Comment by aldihsuhandi** [comment]
> Lgtm

OAWKEOAWKEAOWEKAWOEK

**Review by timothyjulian — APPROVED** [review]

**Review by ChanChanEz — APPROVED** [review]
:rock:

**Review by SetoAditama — APPROVED** [review]
looks good :wakaka:

**Pull request merged**
